package br.com.infox.telas;

import br.com.infox.classes.OrdServ;
import br.com.infox.classes.OrdemDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caiomagno
 * @version Beta
 */
public class FrameRel extends javax.swing.JFrame {

    /**
     * Creates new form FrameRel
     */
    public FrameRel() {
        initComponents();
        lerOS();
    }

    public void lerOS() {
        DefaultTableModel modelo = (DefaultTableModel) this.tbRel.getModel();
        modelo.setNumRows(0);

        OrdemDAO dao = new OrdemDAO();

        for (OrdServ o : dao.listaOrdem()) {
            modelo.addRow(new Object[]{
                o.getNome(),
                o.getOs(), 
                o.getData(),
                o.getTipo(),
                o.getSituacao(), 
                o.getEquipamento(), 
                o.getDefeito(),
                o.getServico(), 
                o.getTecnico(), 
                o.getValor() 
                    
        });

    }
}

public void buscaRel() {
        DefaultTableModel modelo = (DefaultTableModel) this.tbRel.getModel();
        modelo.setNumRows(0);

        String p = txtBusca.getText();
        OrdemDAO ord = new OrdemDAO();
        if (cbBusca.getSelectedItem().equals("Nome")) {
            for (OrdServ o : ord.BuscaRelNome(p)) {

                modelo.addRow(new Object[]{
                    o.getNome(),
                    o.getOs(),
                    o.getData(),
                    o.getTipo(),
                    o.getSituacao(),
                    o.getEquipamento(),
                    o.getDefeito(),
                    o.getServico(),
                    o.getTecnico(),
                    o.getValor()
                });

            }
        } else if (cbBusca.getSelectedItem().equals("Nº OS")) {
            for (OrdServ o : ord.buscaOs(p)) {
                modelo.addRow(new Object[]{
                    o.getNome(),
                    o.getOs(),
                    o.getData(),
                    o.getTipo(),
                    o.getSituacao(),
                    o.getEquipamento(),
                    o.getDefeito(),
                    o.getServico(),
                    o.getTecnico(),
                    o.getValor()
                });
            }
        } else if (cbBusca.getSelectedItem().equals("Situação")) {
            for (OrdServ o : ord.buscaOsSit(p)) {
                modelo.addRow(new Object[]{
                    o.getNome(),
                    o.getOs(),
                    o.getData(),
                    o.getTipo(),
                    o.getSituacao(),
                    o.getEquipamento(),
                    o.getDefeito(),
                    o.getServico(),
                    o.getTecnico(),
                    o.getValor()
                });
            }
        } else if(cbBusca.getSelectedItem().equals("Técnico")){
            
            for (OrdServ o : ord.BuscaRelTec(p)) {
                modelo.addRow(new Object[]{
                    o.getNome(),
                    o.getOs(),
                    o.getData(),
                    o.getTipo(),
                    o.getSituacao(),
                    o.getEquipamento(),
                    o.getDefeito(),
                    o.getServico(),
                    o.getTecnico(),
                    o.getValor()
                });
            }
            
        }else if(cbBusca.getSelectedItem().equals("Tipo")){
            
            for (OrdServ o : ord.buscaOsTipo(p)) {
                modelo.addRow(new Object[]{
                    o.getNome(),
                    o.getOs(),
                    o.getData(),
                    o.getTipo(),
                    o.getSituacao(),
                    o.getEquipamento(),
                    o.getDefeito(),
                    o.getServico(),
                    o.getTecnico(),
                    o.getValor()
                });
            }
        }
        
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbBusca = new javax.swing.JComboBox<>();
        txtBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnImprimiRel = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimBusca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Serviços");

        jLabel1.setText("Busca por:");

        cbBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Nº OS", "Situação", "Tipo", "Técnico" }));
        cbBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscaActionPerformed(evt);
            }
        });

        tbRel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Nº OS", "Data OS", "Tipo", "Situação", "Equipamento", "Defeito", "Serviço", "Tecnico", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbRel);
        if (tbRel.getColumnModel().getColumnCount() > 0) {
            tbRel.getColumnModel().getColumn(0).setPreferredWidth(200);
            tbRel.getColumnModel().getColumn(1).setPreferredWidth(80);
            tbRel.getColumnModel().getColumn(2).setPreferredWidth(170);
            tbRel.getColumnModel().getColumn(3).setPreferredWidth(200);
            tbRel.getColumnModel().getColumn(4).setPreferredWidth(200);
            tbRel.getColumnModel().getColumn(5).setPreferredWidth(200);
            tbRel.getColumnModel().getColumn(6).setPreferredWidth(150);
            tbRel.getColumnModel().getColumn(7).setPreferredWidth(150);
            tbRel.getColumnModel().getColumn(8).setPreferredWidth(150);
            tbRel.getColumnModel().getColumn(9).setPreferredWidth(80);
        }

        jButton1.setText("Sair do Relatório");

        btnImprimiRel.setText("Imprimir Relatório");
        btnImprimiRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimiRelActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimBusca.setText("Limpar Busca");
        btnLimBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnLimBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(btnImprimiRel)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(9, 9, 9)
                .addComponent(btnLimBusca)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnImprimiRel))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1024, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBuscaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
        
            buscaRel();
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnLimBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimBuscaActionPerformed
        // TODO add your handling code here:
        lerOS();
        txtBusca.setText(null);
    }//GEN-LAST:event_btnLimBuscaActionPerformed

    private void btnImprimiRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimiRelActionPerformed
        // TODO add your handling code here:
        /*Document doc = new Document();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream("users/caiomagno/Relatorio.pdf"));
            doc.open();
            
            doc.add( new Paragraph("Cabeçalho"));
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(FrameRel.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            doc.close();
        }
        
        try {
            Desktop.getDesktop().open(new File("users/caiomagno/Relatorio.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(FrameRel.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnImprimiRelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRel.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRel.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRel.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRel.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimiRel;
    private javax.swing.JButton btnLimBusca;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbBusca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRel;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
