package br.com.infox.telas;

import br.com.infox.classes.OrdServ;
import br.com.infox.classes.OrdemDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Caio Magno
 * @version Beta
 */
public class TelaTodasOS extends javax.swing.JFrame {

    

    public TelaTodasOS() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) this.tbOs.getModel();
        tbOs.setRowSorter(new TableRowSorter(modelo));
        readOs();
    }

    //Metodo responsavel por popular a tabela tbOs que é referente ao relatório
    public void readOs() {
        DefaultTableModel modelo = (DefaultTableModel) this.tbOs.getModel();
        modelo.setNumRows(0);

        //Objeto onde foram armazenados os dados referentes a tabela de OS com nome do cliente
        OrdemDAO ord = new OrdemDAO();

        //Obtém os dados para popular a JTable refetente a todas OS
        for (OrdServ o : ord.listaOrdem()) {
            modelo.addRow(new Object[]{
                o.getNome(), //1
                o.getOs(), //2
                o.getSituacao(), //3
                o.getEquipamento(), //4
                o.getServico(), //5
                o.getValor(), //6
                o.getTelefone(),
                o.getData(), //7
                o.getTecnico(), //8
                
            });
        }
        
    }
    
        //Metodo responsavel por buscar uma OS pelo nome do cliente
       public void readOs2() {
        DefaultTableModel modelo = (DefaultTableModel) this.tbOs.getModel();
        modelo.setNumRows(0);

        //Objeto onde foram armazenados os dados referentes a tabela de OS com nome do cliente
        OrdemDAO ord = new OrdemDAO();
        
        String p = txtPesOs.getText();
           //System.out.println(p);

        //Obtém os dados para popular a JTable 
        for (OrdServ o : ord.pequisa(p)) {
            modelo.addRow(new Object[]{
                o.getNome(),
                o.getOs(),
                o.getSituacao(),
                o.getEquipamento(),
                o.getServico(),
                o.getValor(),
                o.getTelefone(),
                o.getData(),
                o.getTecnico(),
                
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbOs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesOs = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Todas as Ordens de Serviço");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        tbOs.setAutoCreateRowSorter(true);
        tbOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome Cliente", "Nº OS", "Situação", "Equipamento", "Serviço", "Valor", "Telefone", "Data OS", "Técnico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbOs.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tbOsComponentShown(evt);
            }
        });
        tbOs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbOsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbOs);
        if (tbOs.getColumnModel().getColumnCount() > 0) {
            tbOs.getColumnModel().getColumn(0).setPreferredWidth(300);
            tbOs.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbOs.getColumnModel().getColumn(3).setPreferredWidth(250);
            tbOs.getColumnModel().getColumn(4).setPreferredWidth(200);
            tbOs.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbOs.getColumnModel().getColumn(6).setPreferredWidth(250);
            tbOs.getColumnModel().getColumn(7).setPreferredWidth(250);
        }

        jLabel1.setText("Nome Cliente:");

        txtPesOs.setToolTipText("Opção Bloqueada");
        txtPesOs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesOsKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesOs, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1020, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbOsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbOsKeyPressed
        // TODO add your handling code here:
        // ReadTable();
    }//GEN-LAST:event_tbOsKeyPressed

    private void tbOsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbOsComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_tbOsComponentShown

    private void txtPesOsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesOsKeyReleased
        
        if(txtPesOs.getText().equals(null))
        {
            readOs2();
        }else{
            readOs();
        }
       
    }//GEN-LAST:event_txtPesOsKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        readOs2();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTodasOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTodasOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTodasOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTodasOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTodasOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbOs;
    private javax.swing.JTextField txtPesOs;
    // End of variables declaration//GEN-END:variables
}
