package br.com.infox.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import br.com.infox.dao.ModuloConexao;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author caiomagno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        mainCad = new javax.swing.JMenu();
        mainCadCli = new javax.swing.JMenuItem();
        mainOs = new javax.swing.JMenuItem();
        mainUser = new javax.swing.JMenuItem();
        mainRel = new javax.swing.JMenu();
        mainRelServ = new javax.swing.JMenuItem();
        mainAju = new javax.swing.JMenu();
        mainAjuSob = new javax.swing.JMenuItem();
        mainOp = new javax.swing.JMenu();
        mainSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CM Informática - Tela Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setForeground(new java.awt.Color(0, 51, 204));
        desktop.setPreferredSize(new java.awt.Dimension(6, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/logo_cminfo-e1609890546900.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        lblData.setText("Data");

        mainCad.setText("Cadastro");

        mainCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.META_MASK));
        mainCadCli.setText("Cliente");
        mainCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainCadCliActionPerformed(evt);
            }
        });
        mainCad.add(mainCadCli);

        mainOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.META_MASK));
        mainOs.setText("Ordem de Serviço");
        mainOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainOsActionPerformed(evt);
            }
        });
        mainCad.add(mainOs);

        mainUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.META_MASK));
        mainUser.setText("Usuários");
        mainUser.setEnabled(false);
        mainUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainUserActionPerformed(evt);
            }
        });
        mainCad.add(mainUser);

        menu.add(mainCad);

        mainRel.setText("Relatório");
        mainRel.setEnabled(false);

        mainRelServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        mainRelServ.setText("Serviços");
        mainRelServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainRelServActionPerformed(evt);
            }
        });
        mainRel.add(mainRelServ);

        menu.add(mainRel);

        mainAju.setText("Ajuda");

        mainAjuSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.META_MASK));
        mainAjuSob.setText("Sobre");
        mainAjuSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAjuSobActionPerformed(evt);
            }
        });
        mainAju.add(mainAjuSob);

        menu.add(mainAju);

        mainOp.setText("Opções");

        mainSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.META_MASK));
        mainSair.setText("Sair");
        mainSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSairActionPerformed(evt);
            }
        });
        mainOp.add(mainSair);

        menu.add(mainOp);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario)
                    .addComponent(lblData))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(lblUsuario)
                .addGap(32, 32, 32)
                .addComponent(lblData)
                .addContainerGap(464, Short.MAX_VALUE))
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1200, 721));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainCadCliActionPerformed
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);
    }//GEN-LAST:event_mainCadCliActionPerformed

    private void mainSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSairActionPerformed
        // Exibe uma caixa de Dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            try {
                conexao.close();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }
    }//GEN-LAST:event_mainSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As Linhas abaixo substituem as labels data e usuário com data prevista pelo sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.DEFAULT);
        lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void mainAjuSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAjuSobActionPerformed
        //Chama a tela Sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);

    }//GEN-LAST:event_mainAjuSobActionPerformed

    private void mainUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainUserActionPerformed
        // As linhas abaixo abriram o InternalFrame dentro do Objeto Desktop
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_mainUserActionPerformed

    private void mainOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainOsActionPerformed
        TelaOs os = new TelaOs();
        os.setVisible(true);
        desktop.add(os);
    }//GEN-LAST:event_mainOsActionPerformed

    private void mainRelServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainRelServActionPerformed

        FrameRel rel = new FrameRel();
        rel.setVisible(true);
        desktop.add(rel);
    }//GEN-LAST:event_mainRelServActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu mainAju;
    private javax.swing.JMenuItem mainAjuSob;
    private javax.swing.JMenu mainCad;
    private javax.swing.JMenuItem mainCadCli;
    private javax.swing.JMenu mainOp;
    private javax.swing.JMenuItem mainOs;
    public static javax.swing.JMenu mainRel;
    private javax.swing.JMenuItem mainRelServ;
    private javax.swing.JMenuItem mainSair;
    public static javax.swing.JMenuItem mainUser;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
